# -*- coding: utf-8 -*-
"""translator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vuOrOqnG3ac_2Z9-lPqVUdxi6DY_rFBe
"""

!pip install accelerate gTTS gradio transformers

from transformers import AutoModelForCausalLM, AutoTokenizer
from gtts import gTTS
import torch
import gradio as gr

device = "cuda" if torch.cuda.is_available() else "cpu"

from transformers import T5ForConditionalGeneration, T5Tokenizer

language_model_name = "t5-small"  # Note: path should be "t5-small" not "google-t5/t5-small"
language_model = T5ForConditionalGeneration.from_pretrained(
    language_model_name,
    torch_dtype="auto",
    device_map="auto"
)
tokenizer = T5Tokenizer.from_pretrained(language_model_name)

def process_input(input_text, action):
    if action == "Translate to English":
        prefix = "translate to English: "
        lang = "en"
    elif action == "Translate to Chinese":
        prefix = "translate to Chinese: "
        lang = "zh-cn"
    elif action == "Translate to Japanese":
        prefix = "translate to Japanese: "
        lang = "ja"
    else:
        prefix = "respond: "
        lang = "en"

    input_text = prefix + input_text

    # T5 specific encoding and generation
    inputs = tokenizer(input_text, return_tensors="pt").to(device)
    outputs = language_model.generate(
        inputs.input_ids,
        max_new_tokens=512,
        num_beams=4,
        early_stopping=True
    )

    output_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return output_text, lang

def process_input(input_text, action):
    if action == "Translate to English":
        prompt = f"Please translate the following text into English：{input_text}"
        lang = "en"
    elif action == "Translate to Chinese":
        prompt = f"Please translate the following text into Chinese：{input_text}"
        lang = "zh-cn"
    elif action == "Translate to Japanese":
        prompt = f"Please translate the following text into Japanese：{input_text}"
        lang = "ja"
    else:
        prompt = input_text
        lang = "en"

    messages = [
        {"role": "system", "content": "You are a helpful AI assistant."},
        {"role": "user", "content": prompt}
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(device)

    generated_ids = language_model.generate(
        model_inputs.input_ids,
        max_new_tokens=512
    )
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]

    output_text = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    return output_text, lang

def text_to_speech(text, lang):
    tts = gTTS(text=text, lang=lang)
    filename = "output_audio.mp3"
    tts.save(filename)
    return filename

def handle_interaction(input_text, action):
    output_text, lang = process_input(input_text, action)
    audio_filename = text_to_speech(output_text, lang)
    return output_text, audio_filename

action_options = ["Translate to English", "Translate to Chinese", "Translate to Japanese", "Chat"]

iface = gr.Interface(
    fn=handle_interaction,
    inputs=[
        gr.Textbox(label="input text"),
        gr.Dropdown(action_options, label="select action")
    ],
    outputs=[
        gr.Textbox(label="output text"),
        gr.Audio(label="output audio")
    ],
    title="Translation and Chat App using AI",
    description="Translate input text or chat based on the selected action.",
    theme= "gradio/soft"
)

if __name__ == "__main__":
    iface.launch(share=True)

